### PR TITLE
Cleaning up code.

### PR DESCRIPTION
**Pull request by rwithik**

### CODE REVIEW

**Comment by abhijithneilabraham** [comment]
lol, the catsound feature is not implemented by me, anyway can you do it like, playing the sounds only until the keyboard loop runs and stop the execution of sound after that

**Comment by rwithik** [comment]
> lol, the catsound feature is not implemented by me, anyway can you do it like, playing the sounds only until the keyboard loop runs and stop the execution of sound after that


As of now, there is no keyboard "loop". Idk if you meant it that way, but now the output is c cat sounds and c random characters.

**Comment by abhijithneilabraham** [comment]
The catran function is called inside the loop. hehe

**Comment by abhijithneilabraham** [comment]
> The catran function is called inside the loop. hehe

And each key would be generated after full execution of each sound, which actually sucks. Either use another package or stop executing the function abruptly.

**Comment by rwithik** [comment]
> The catran function is called inside the loop. hehe

I expect more characters if a cat runs through my keyboard lol

**Comment by abhijithneilabraham** [comment]
> > The catran function is called inside the loop. hehe
> 
> I expect more characters if a cat runs through my keyboard lol

Yep sure we could use a while loop and break it with some sequence of chars .Do that.

**Comment by rwithik** [comment]
> And each key would be generated after full execution of each sound, which actually sucks. Either use another package or stop executing the function abruptly.

This can be done, with the `playsound` package, but it works only on Ubuntu 14.04 and elementaryOS. From the docs:

> Known to work on Ubuntu 14.04 and ElementaryOS Loki. Support for the block argument is currently not implemented.

**Comment by abhijithneilabraham** [comment]
> > And each key would be generated after full execution of each sound, which actually sucks. Either use another package or stop executing the function abruptly.
> 
> This can be done, with the `playsound` package, but it works only on Ubuntu 14.04 and elementaryOS. From the docs:
> 
> > Known to work on Ubuntu 14.04 and ElementaryOS Loki. Support for the block argument is currently not implemented.

ahh,thats what wrong with my cat...It's been running on a macos. Bad kitty

**Comment by abhijithneilabraham** [comment]
Okay.You win the tee.

**Pull request merged**
